export const EMPLOYEES = [
  { id: 'LBR001', name: 'Ramesh Yadav', gender: 'male', role: 'Machine Operator', rate: 450, shift: '12-hour' },
  { id: 'LBR002', name: 'Suresh Chenna', gender: 'male', role: 'Helper', rate: 350, shift: '12-hour' },
  { id: 'LBR003', name: 'Anita Devi', gender: 'female', role: 'Packaging Labour', rate: 320, shift: '9-hour' },
  { id: 'LBR004', name: 'Kavita Kumari', gender: 'female', role: 'Quality Checker', rate: 380, shift: '9-hour' },
  { id: 'LBR005', name: 'Amit Singh', gender: 'male', role: 'Welder', rate: 550, shift: '12-hour' },
  { id: 'LBR006', name: 'Rahul Prasad', gender: 'male', role: 'Loader', rate: 300, shift: '12-hour' },
  { id: 'LBR007', name: 'Sunita Bai', gender: 'female', role: 'Assembler', rate: 340, shift: '9-hour' },
  { id: 'STF001', name: 'Vikram Sharma', gender: 'male', role: 'Floor Supervisor', rate: 750, shift: '12-hour' },
  { id: 'STF002', name: 'Neha Gupta', gender: 'female', role: 'Unit Manager', rate: 900, shift: '9-hour' },
];

export const ATTENDANCE_RECORDS = [
  {
    id: 'REC001',
    employeeId: 'LBR001',
    employeeName: 'Ramesh Yadav',
    date: '2024-05-15',
    shiftType: '12-hour',
    clockIn: '08:00',
    clockOut: '20:15',
    hours: 12.25,
    earnings: 5512.5,
    status: 'Verified',
  },
  {
    id: 'REC002',
    employeeId: 'LBR003',
    employeeName: 'Anita Devi',
    date: '2024-05-15',
    shiftType: '9-hour',
    clockIn: '09:00',
    clockOut: '18:00',
    hours: 9.0,
    earnings: 2880,
    status: 'Verified',
  },
  {
    id: 'REC003',
    employeeId: 'STF001',
    employeeName: 'Vikram Sharma',
    date: '2024-05-14',
    shiftType: '12-hour',
    clockIn: '08:00',
    clockOut: '20:45',
    hours: 12.75,
    earnings: 9562.5,
    status: 'Overtime',
  },
  {
    id: 'REC004',
    employeeId: 'LBR004',
    employeeName: 'Kavita Kumari',
    date: '2024-05-14',
    shiftType: '9-hour',
    clockIn: '09:15',
    clockOut: '18:00',
    hours: 8.75,
    earnings: 3325,
    status: 'Verified',
  },
];
