export const EMPLOYEES = [
  { id: 'EMP001', name: 'Arjun Mehta', gender: 'male', role: 'Machine Operator', rate: 450, shift: '12-hour' },
  { id: 'EMP002', name: 'Priya Sharma', gender: 'female', role: 'Quality Lead', rate: 550, shift: '9-hour' },
  { id: 'EMP003', name: 'Rajesh Kumar', gender: 'male', role: 'Floor Supervisor', rate: 650, shift: '12-hour' },
  { id: 'EMP004', name: 'Ananya Iyer', gender: 'female', role: 'Logistics Coord', rate: 400, shift: '9-hour' },
  { id: 'EMP005', name: 'Vikram Singh', gender: 'male', role: 'Maintenance Tech', rate: 600, shift: '12-hour' },
  { id: 'EMP006', name: 'Siddharth Rao', gender: 'male', role: 'Packaging Specialist', rate: 380, shift: '12-hour' },
  { id: 'EMP007', name: 'Meera Kulkarni', gender: 'female', role: 'Inventory Manager', rate: 520, shift: '9-hour' },
];

export const ATTENDANCE_RECORDS = [
  {
    id: 'REC001',
    employeeId: 'EMP001',
    employeeName: 'Arjun Mehta',
    date: '2024-05-15',
    shiftType: '12-hour',
    clockIn: '08:00',
    clockOut: '20:15',
    hours: 12.25,
    earnings: 5512.5,
    status: 'Verified',
  },
  {
    id: 'REC002',
    employeeId: 'EMP002',
    employeeName: 'Priya Sharma',
    date: '2024-05-15',
    shiftType: '9-hour',
    clockIn: '09:00',
    clockOut: '18:00',
    hours: 9.0,
    earnings: 4950,
    status: 'Verified',
  },
  {
    id: 'REC003',
    employeeId: 'EMP003',
    employeeName: 'Rajesh Kumar',
    date: '2024-05-14',
    shiftType: '12-hour',
    clockIn: '08:00',
    clockOut: '20:45',
    hours: 12.75,
    earnings: 8287.5,
    status: 'Overtime',
  },
  {
    id: 'REC004',
    employeeId: 'EMP004',
    employeeName: 'Ananya Iyer',
    date: '2024-05-14',
    shiftType: '9-hour',
    clockIn: '09:15',
    clockOut: '18:00',
    hours: 8.75,
    earnings: 3500,
    status: 'Verified',
  },
];
